### ISSUE TITLE
Assign a new user as an admin...dump

### ISSUE THREAD

**Issue by khyoz** [raylight75/cms#1]
If I want to add a user as an admin...
![2017-06-19 06_51_50-admin backend](https://user-images.githubusercontent.com/26684951/27270084-218ce8c4-54bc-11e7-84ee-01ffed393d1e.png)
and save....I got an error
![2017-06-19 06_48_43-localhost_myshop_public_backend_users_7](https://user-images.githubusercontent.com/26684951/27270029-a434f196-54bb-11e7-853c-c9cdb6c7a2e8.png)
If I assign a user role...success, all is ok, no dump

and very nice project !

**Comment by raylight75** [comment]
Thanks for feedback, yes. It's a bug I will fix that soon

**Comment by raylight75** [comment]
I don't have internet connection last 3 day but today I was able to test functionality and seems that everything working fine. Just create new user  on demo site and add admin role to this user.

**Comment by khyoz** [comment]
Cannot see any changes in your code here...and we cannot test as admin on your demo site. 
So problem is still the same for me. In my screenshot you can see I was connected as admin on my demo.
Or maybe you forget an update in this repo that was only available on your local site.

**Comment by raylight75** [comment]
![admin2](https://user-images.githubusercontent.com/11574293/27510695-46ae6ab2-591f-11e7-8e7a-949d3855bd85.jpg)
I can't reproduce error, this is the reason why i'm not changing code for now. You can check database and you must have for example user with id=7 and in role_user table a user with role_id =1.
Try to drop database and import again from repository.
I will leave the issue open for future investigations.
