### ISSUE TITLE
ErrorException (E_WARNING) "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?

### ISSUE THREAD

**Issue by uniquechukwuma** [raylight75/cms#12]
Please i keep getting this error when i click on order, brand, category at the backend. i cloned the project did composer update. please help

ErrorException (E_WARNING)
"continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?

 $methodClass = get_class($this->relation);
            switch ($methodClass) {
                case 'Illuminate\Database\Eloquent\Relations\BelongsToMany':
 
                    $old_data = $this->relation->get()->modelKeys();
                    $new_data = explode($this->serialization_sep, $data);
 
                    $this->relation->detach($old_data);
 
                    if ($data=='') {
                        continue;
                    }
 
                    if (is_callable($this->extra_attributes)) {
                        $callable = $this->extra_attributes;
                        foreach ($new_data as $d) {
                            $this->relation->attach($d, $callable($d));
                        }
                    } elseif (is_array($this->extra_attributes)) {
                        $this->relation->attach($new_data, $this->extra_attributes);
                    }
 
                    break;
                case 'Illuminate\Database\Eloquent\Relations\HasOne':
 
                    if (isset($this->model_relations[$this->rel_name])) {

**Comment by raylight75** [comment]
This is a problem with PHP version, the project is not tested with PHP version 7 and above see [https://github.com/composer/composer/issues/7783](url)

**Comment by uniquechukwuma** [comment]
please you closed the ticket but i have not solved the problem can you help?
