### ISSUE TITLE
PHP Warning:  require(E:\project\ecms\cms\bootstrap./vendor/autoload.php):

### ISSUE THREAD

**Issue by azeem6990** [raylight75/cms#18]
php artisan migrate
PHP Warning:  require(E:\project\ecms\cms\bootstrap./vendor/autoload.php): failed to open stream: No such file or directory in E:\project\ecms\cms\bootstrap\autoload.php on line 17

Warning: require(E:\project\ecms\cms\bootstrap./vendor/autoload.php): failed to open stream: No such file or directory in E:\project\ecms\cms\bootstrap\autoload.php on line 17
PHP Fatal error:  require(): Failed opening required 'E:\project\ecms\cms\bootstrap./vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in E:\project\ecms\cms\bootstrap\autoload.php on line 17

Fatal error: require(): Failed opening required 'E:\project\ecms\cms\bootstrap./vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in E:\project\ecms\cms\bootstrap\autoload.php on line 17

**Comment by raylight75** [comment]
Can you provide more info,  did you run composer install , etc..

**Comment by raylight75** [comment]
Without additional information  I will close this. Feel free to open if you provide information
