### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by zidingz** [raylight75/cms#19]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by raylight75** [comment]
It's a free repository and I do not provide security patches or support.

**Comment by zidingz** [comment]
Hey @raylight75, the user who submitted this report, @nitesculucian, also submitted a patch for this issue, so you won't have to write one yourself!

I've authenticated your GitHub user to access the reports below. If you encounter difficulty accessing the reports, just let me know. Thanks!

https://huntr.dev/bounties/536c139d-16e8-48aa-aa37-6e833e7122ed/
https://huntr.dev/bounties/f61179ad-ac34-46ff-9b3d-f3a23818a5d6/
https://huntr.dev/bounties/44192396-6d8d-42a7-8d2d-2dadefa795e0/
