### ISSUE TITLE
Call to undefined method Illuminate\Database\Query\Builder::getOtherKey()

### ISSUE THREAD

**Issue by leezene** [raylight75/cms#3]
when I clicked on add product or edit products, this error shows up.

**Comment by raylight75** [comment]
Can you provide more info because this error is connected with Rapyd-Laravel package see problem here [https://github.com/zofe/rapyd-laravel/pull/394](url)

**Comment by raylight75** [comment]
So if you have problem when updating to Laravel 5.5 copy this code to Zofe/rapyd/src/DataForm/Field/Field.php From line 140 :
`if (method_exists($this->relation, 'getQualifiedRelatedPivotKeyName')) {
                    $this->rel_other_key = $this->relation->getQualifiedRelatedPivotKeyName();
                } elseif (method_exists($this->relation, 'getQualifiedRelatedKeyName')) {
                    $this->rel_other_key = $this->relation->getQualifiedRelatedKeyName();
                } else {
                    $this->rel_other_key = $this->relation->getOtherKey();
                }`
