### ISSUE TITLE
Installation request for zofe/rapyd dev-master

### ISSUE THREAD

**Issue by maan81** [raylight75/cms#8]
After cloning & while doing `composer update` I am getting the error :

   - Installation request for zofe/rapyd dev-master
   - Conclusion: don't install intervention/image 2.4.2
   - .......
   ...... 
   ......

I am using xampp 7.2.8 , composer 1.7.1, Windows 10 in Virtualbox. 

I have cloned the created database, but unable to run the `composer update` or `php artisan migrate` as mentioned in https://github.com/raylight75/cms#official-documentation .

Could someone help me ?

**Comment by raylight75** [comment]
I will try to reproduce error soon and i will leave comment

**Comment by raylight75** [comment]
I dont't have such problem , but some of the packages have been upgraded and you have to meet the installation requirements. For Zofe/rapyd they are :
` "require": {
        "php": ">=7.1",
        "illuminate/support": "~5.6",
        "laravelcollective/html": "~5.6",
        "intervention/image": "2.4.2",
        "zofe/burp": "2.*"
    },`
I don't have time now but soon i will edit composer.json for now just edit composer.json with required versions

**Comment by maan81** [comment]
Please upload the whole composer.json file. I am still having problems in composer update.

**Comment by raylight75** [comment]
This issue may also be fixed by updating your version of Laravel to v5.6 or  just using a lower version of zofe/rapyd.
