### ISSUE TITLE
"laravelCollective/html" and "nesbot/carbon" compatibility issue

### ISSUE THREAD

**Issue by mashooquecs** [raylight75/cms#9]
Hello.
After downloading "raylight75/cms" when I'm updating composer following Two errors occur
1. "Zofe/rapyd dev-master" requires "laravelCollective/html ~5.6"
2. laravel/framework v5.5.9 requires nesbot/carbon ~1.20

I could not get that, Does anyone has solution?
I've attached snapshot of that errors
![raylight75issue](https://user-images.githubusercontent.com/37797357/47224606-5c9ba880-d3d5-11e8-8126-74c9b22f87ab.PNG)

**Comment by raylight75** [comment]
You have to meet the installation requirements. For Zofe/rapyd they are :
"require": { "php": ">=7.1", "illuminate/support": "~5.6", "laravelcollective/html": "~5.6", "intervention/image": "2.4.2", "zofe/burp": "2.*" }. Change in composer file packages to required version.
So if Laravel 5.5.9 need Carbon 1.20 change line "nesbot/carbon": "dev-master" to "nesbot/carbon": " ~1.20" and so on.  I will edit composer.json soon but packages are constantly updated.

**Comment by raylight75** [comment]
Composer.json is updated to Laravel 5.6

**Comment by mashooquecs** [comment]
#raylight75 Thanks!
That was about requirements as you've told.
